server:
  port: 9090
        
# spring Configs        
spring:
  profiles:
    active: local
    #active: production
        
aws:
  region: us-east-1
  sqs:
    queue:
      product:
        events:
          name: product-events